### ISSUE TITLE
Non-ASCII characters in path names cause the .ensime generator to crash

### ISSUE THREAD

**Issue by teozkr** [sublimescala/sublime-ensime#79]
I was trying to generate ENSIME config for [slick][] which was cloned to the folder `/home/teo/Hämtningar/slick`. It worked without problems from `/home/teo/downloads/slick`. Traceback below:

```pytb
Traceback (most recent call last):
  File "./dotensime.py", line 283, in <lambda>
  File "./ensime.py", line 863, in init_project
  File "./rpc.py", line 311, in wrapped
  File "./ensime.py", line 474, in async_req
  File "./sexp.py", line 204, in to_string
  File "./sexp.py", line 204, in to_string
  File "./sexp.py", line 204, in to_string
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 164: ordinal not in range(128)
Traceback (most recent call last):
  File "./dotensime.py", line 283, in <lambda>
  File "./ensime.py", line 863, in init_project
  File "./rpc.py", line 311, in wrapped
  File "./ensime.py", line 474, in async_req
  File "./sexp.py", line 204, in to_string
  File "./sexp.py", line 204, in to_string
  File "./sexp.py", line 204, in to_string
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 164: ordinal not in range(128)
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./ensime.py", line 1189, in run
  File "./dotensime.py", line 41, in error_no_config
  File "./dotensime.py", line 195, in create
  File "./dotensime.py", line 77, in do_create
  File "./dotensime.py", line 88, in confirm_and_proceed
  File "./dotensime.py", line 109, in create_for_single_folder
  File "./dotensime.py", line 122, in confirm_sbt
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 11: ordinal not in range(128)
```

[slick]: https://github.com/slick/slick

**Comment by rorygraves** [comment]
Should work now in https://github.com/ensime/ensime-sublime
