### ISSUE TITLE
TypeError: embedded NUL character

### ISSUE THREAD

**Issue by lvicentesanchez** [sublimescala/sublime-ensime#88]
I'm using SublimeText/3 (rev 3.047) under Ubuntu and I didn't notice them before... but on sublime console I have a lot of messages like this:

Traceback (most recent call last):
  File "/opt/sublimetext3/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/ensime.py", line 183, in on_activated
    return self._invoke(view, "on_activated")
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/ensime.py", line 156, in _invoke
    if handler: return handler(*args)
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/ensime.py", line 937, in on_activated
    self.colorize()
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/ensime.py", line 118, in colorize
    def colorize(self, view = "default"): self._invoke_view_colorer("colorize", view)
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/ensime.py", line 109, in _invoke_view_colorer
    getattr(colorer, method)(*args)
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/ensime.py", line 965, in colorize
    self.redraw_highlights()
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/ensime.py", line 1010, in redraw_highlights
    self.redraw_breakpoints()
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/ensime.py", line 1075, in redraw_breakpoints
    relevant_breakpoints = [breakpoint for breakpoint in self.env.breakpoints if same_paths(
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/ensime.py", line 1076, in <listcomp>
    breakpoint.file_name, self.v.file_name())]
  File "/home/lvicentesanchez/.config/sublime-text-3/Packages/Ensime/paths.py", line 39, in same_paths
    path1_normalized = os.path.normcase(os.path.realpath(path1))
  File "X/posixpath.py", line 408, in realpath
  File "X/posixpath.py", line 164, in islink
TypeError: embedded NUL character

**Comment by rorygraves** [comment]
I have not seen this under the updated plugin  - closing - please reopen on https://github.com/ensime/ensime-sublime if you see it again
