### ISSUE TITLE
Errors not getting highlighted (console output related to icon not being a string)

### ISSUE THREAD

**Issue by elkorn** [sublimescala/sublime-ensime#95]
I'm using the ST3 branch of sublime-ensime and have encountered the problem of errors not being highlighted within the code.

Passing `'circle'` as the icon in the config did not help the cause.

The only information I'm getting is the following:

```
Traceback (most recent call last):
  File "/home/helluin/.config/sublime-text-3/Packages/Ensime/ensime.py", line 636, in message_scala_notes
    self._update_note_ui()
  File "/home/helluin/.config/sublime-text-3/Packages/Ensime/ensime.py", line 622, in _update_note_ui
    self.redraw_all_highlights()
  File "/home/helluin/.config/sublime-text-3/Packages/Ensime/ensime.py", line 123, in redraw_all_highlights
    def redraw_all_highlights(self): self._invoke_all_colorers("redraw_highlights")
  File "/home/helluin/.config/sublime-text-3/Packages/Ensime/ensime.py", line 116, in _invoke_all_colorers
    getattr(colorer, method)(*args)
  File "/home/helluin/.config/sublime-text-3/Packages/Ensime/ensime.py", line 994, in redraw_highlights
    sublime.DRAW_EMPTY_AS_OVERWRITE)
  File "/opt/sublime_text/sublime.py", line 859, in add_regions
    raise ValueError("icon must be a string")
ValueError: icon must be a string
```

Have You stumbled upon this issue in the master branch?

**Comment by rorygraves** [comment]
I believe this is fixed on the new build
